#!/bin/bash -x

set -e

export PATH=$PATH:/home/cdodt/bin

ARGS="-Cav -F --inplace --delete"
RSYNC="rsync $ARGS"
REMOTEDIR=backups/`hostname -s`
DEST="goonmill.org:/home/cdodt/$REMOTEDIR/"

FAILADDRESS="corydodt+hello@gmail.com"

echo Backing up `hostname` on `date -I`

failmail() {
    message="$1"
    echo "$message" | mail -s `hostname -s`" backup failed; reason shown below" "$FAILADDRESS"
}

cd ~cdodt

TOHGFILES='.gvimrc
.screenrc
.zshrc
.zsh
/usr/local/bin/xvim
'

HOMEFILES='.compiz
.config
backgrounds
bin
cory.kdb
Desktop
.dput.cf
.gnupg
.gconf
.gnome2
.hgrc
.HotheadGames
.java
.local
.maptool
.openoffice.org
packages.txt
.pdbrc
.prism
.purple
.pydistutils.cfg
.pypirc
.ssh
.mozilla
RecentDownloads
.Skype
.WorldOfGoo
'

ROOTFILES='/etc/modules
/etc/vim
/etc/udev/rules.d/99-android.rules
/etc/pm/sleep.d/50cdd-fix-mousekeys
/usr/local/bin/xvim
'

dpkg-origins > packages.txt || failmail "Could not run dpkg-origins"

$RSYNC $TOHGFILES ~/wc/Personal/  # don't fail if this doesn't work

ssh goonmill.org 'mkdir -p '$REMOTEDIR || failmail "Could not create backups dir"
$RSYNC $TOHGFILES $DEST || failmail "Could not rsync TOHGFILES"
$RSYNC $HOMEFILES $DEST || failmail "Could not rsync HOMEFILES"
$RSYNC $ROOTFILES $DEST || failmail "Could not rsync ROOTFILES"

# some stupid programs insist on removing all write permissions.  i guess this
# is a security feature for firefox extensions to prevent sploits in
# extensions mutating other extensions?  whatever, in my backup, it will be
# all writeable.  firefox seems to "fix" (by removing) the +w permission on
# loading anyway, so this won't cause any problems.
ssh goonmill.org 'chmod -R u+w '$REMOTEDIR

