#!/bin/bash -x

set -e

if [ `id` != '0' ]; then
    echo "** Must be root to run $0" 1>&2
    exit 1
fi

echo Backing up `hostname` on `date -I`

# =============================
# command line flags I'm using:
# =============================
# -C --cvs-exclude (use .cvsignore files to determine what to ignore/skip)
# -a --archive (ALL of the following):
#    -r --recursive (descend subdirectories)
#    -l --links (copy symlinks as symlinks)
#    -p --permissions (copy permissions)
#    -g --group (copy group owner)
#    -o --owner (copy user owner)
#    -D --devices (copy devices intact)
#    -t --times (copy times)
# -v --verbose (show what's happening)
# --inplace  (copy files in place over old files, to reduce i/o)
# --delete (when a file in the destination is missing in the source, delete it
#           in the destination)


dest="corydodt@corydodt.strongspace.com:/strongspace/corydodt/home/backups"


args=(-Cav -F --inplace --delete --log-file=/var/log/backup-engraver.log)
sshOptions=(-e "ssh -o IdentityFile=/home/cdodt/.ssh/id_dsa")
rsync=(rsync "${args[@]}" "${sshOptions[@]}")


touch /var/log/backup-engraver.log
chmod 600 /var/log/backup-engraver.log

"${rsync[@]}" /var $dest/engraver.goonmill.org
"${rsync[@]}" /home $dest/engraver.goonmill.org
"${rsync[@]}" /etc $dest/engraver.goonmill.org
"${rsync[@]}" /usr/local $dest/engraver.goonmill.org/usr
"${rsync[@]}" /usr/share/moin $dest/engraver.goonmill.org/usr/share
