#!/bin/bash -x

set -e

ARGS="-Cav -F --inplace --delete"
RSYNC="rsync $ARGS"
DEST="goonmill.org:/home/cdodt/backups/`hostname -s`/"

FAILADDRESS="corydodt+hello@gmail.com"

echo Backing up `hostname` on `date -I`

failmail() {
    message="$1"
    echo "$message" | mail -s "harvester backup failed; reason shown below" "$FAILADDRESS"
}

cd ~cdodt

TOHGFILES='.gvimrc
.screenrc
.vimrc
.vim
.xmodmap
.zshrc
.zsh
'

HOMEFILES='.compiz
.config
backgrounds
bin
cory.kdb
Desktop
.gnupg
.gconf
.gnome2
.hgrc
.HotheadGames
.java
.kde4
.libao
.local
.openoffice.org2
packages.txt
.prism
.purple
.mozilla
RecentDownloads
.Skype
.tomboy
'

ROOTFILES='/etc/X11/xorg.conf
/etc/modules
/etc/modprobe.d/options
'

dpkg-origins > packages.txt || failmail "Could not run dpkg-origins"

$RSYNC $TOHGFILES ~/wc/Personal/  # don't fail if this doesn't work

ssh goonmill.org 'mkdir -p backups/'`hostname -s` || failmail "Could not create backups dir"
$RSYNC $TOHGFILES $DEST || failmail "Could not rsync TOHGFILES"
$RSYNC $HOMEFILES $DEST || failmail "Could not rsync HOMEFILES"
$RSYNC $ROOTFILES $DEST || failmail "Could not rsync ROOTFILES"

