#!/bin/bash
set -e 

cd ~/wc/
hg clone v2 "$1"
cd ~/wc/"$1"/hermes/pyx
cp -v Makefile.include.mosquito Makefile.include.`hostname -s`
cd ../c
cp -v Makefile.include.mosquito Makefile.include.`hostname -s`
cd ../..

echo "Compiling C/pyx code"
make > make.log 2>&1

echo "Fixing up ph script"
sed -e "s:~/h/dev:$1:g
s:erwin:cdodt:g" "$1"/scripts/sample/ph > "$1"/ph

bash scripts/bootstrap
cd ~/wc/
echo "Copying demo directory.."
cp -a v2/demo "$1"/demo
touch "$1"/HERMES2_HOME
makepth "$1"
echo done
