#!/usr/bin/env python
import sys, os

from twisted.python import usage
from twisted.web import microdom, domhelpers


class Options(usage.Options):
    synopsis = "gather <file>"

    def parseArgs(self, file):
        self['file'] = file

    def postOptions(self):
        print domhelpers.gatherTextNodes(microdom.parse(self['file']),
                joinWith=" ")

def run(argv=None):
    if argv is None:
        argv = sys.argv
    o = Options()
    try:
        o.parseOptions(argv[1:])
    except usage.UsageError, e:
        print str(o)
        print str(e)
        return 1

    return 0

if __name__ == '__main__': sys.exit(run())

