#!/usr/bin/env python
import sys
from xml.etree import ElementTree

def usage(exit, message):
    print >> sys.stderr, "Extract all raw text nodes from an xml document."
    print >> sys.stderr, "Usage: gather 'filename.xml'"
    print >> sys.stderr
    print >> sys.stderr, "** %s" % (message,)
    sys.exit(exit)

def run(argv=None):
    if argv is None:
        argv = sys.argv

    if len(argv) < 2:
        usage(1, "No filename.")

    f = argv[1]

    if not hasattr(f, 'read'):
        try:
            f = open(f)
        except EnvironmentError:
            usage(1, "Could not open %s." % (f,))

    p = ElementTree.parse(f)

    for c in p.getroot().getiterator():
        if c.text: print c.text, 

if __name__ == '__main__':
    run()
