#!/bin/bash

# Run the given command; if it fails, email each address with the output

if [ "$#" -ne 2 ]; then 
    echo "** Usage: mailunless 'command line' 'address address ...'" 1>&2
    exit 1
fi

addresses="$2"
command="$1"

output=`eval $1 2>&1`
status=$?

if [ "$status" -ne 0 ]; then
    mail -s "Command failed: $command" $addresses <<< $output
fi
