#!/bin/bash

# screenpick: run screen, unless there is already a screen session. If a
# screen session is already running, display a console menu. You can either
# choose an existing session or start a new one.

status=`screen -q -ls;echo $?`
if [ "$status" == 9 ]; then
    selection="new"

else
    screens=`screen -ls | grep '^'$'\t'`

    unset tags
    export IFS=$'\n'
    for screen in $screens; do
        tags+=(`echo "$screen" | awk '{print $1}'`)
        tags+=(`echo "$screen" | sed 's/^\s*//;s/\s*$//;s/\t/ /g'`)
    done
    tags+=(new New)

    for t in "${tags[@]}"; do echo $t; done

    COLUMNS=$(tput cols)
    LINES=$(tput lines)
    selection=`whiptail --menu $'\n\nChoose a screen\n\n\n\n\n\n\n\n\n\n\n' $LINES $COLUMNS 5 "${tags[@]}" 2>&1 > /dev/tty`
fi

if [ "$selection" == "new" ]; then
    screen
else
    screen -d -r $selection
fi

