#!/bin/bash


vimtab() {
    # a bug in gvim remote means directories don't open until you have visited
    # another buffer. Adding +e (edit file) seems to refresh the tab and fix
    # that.
    command gvim --remote-tab-silent +e "$@"
}

waittab() {
    command gvim --remote-tab-silent-wait +e "$@"
}

args="$@"

if [ "${#args}" -eq 0 ]; then
    args="."
fi

# directories don't open correctly with my vimrc, so add a path element after
# them.
convertedArgs=()
for a in ${args}; do
    if [ -d "$a" ]; then
        a="${a}/."
    fi
    convertedArgs+=( "${a}" )
done

xvim_ () {
    if [ "${#convertedArgs[@]}" -eq 1 ] && [ "${convertedArgs[0]}" = "-" ]; then
        tf=`tempfile -pvim-r_ -d/tmp`
        cat > $tf
        (
            waittab "$tf"
            rm -f $tf
        ) > /dev/null 2>&1 &
    else
        vimtab "${convertedArgs[@]}"
    fi
}

xvim_ "${convertedArgs[@]}"
