all:
	rst2html --stylesheet=my.css subversion_for_zbdev.txt > subversion_for_zbdev.html
	rst2s5 win32_install.txt > win32_install.html
	rst2s5 unix_install.txt > unix_install.html
	rst2s5 unix_get_familiar.txt > unix_get_familiar.html
