#!/bin/zsh
autoload colors
colors

# print the color string of an escape
esccolor () {
    bold="${color[${2}]}"
    bold="${bold:+;}${bold:-}"
    echo -n "\e[${color[$1]}${bold}m"
}

colorOff=`esccolor none`

_border='________________________________________________________________________________________________________________________________________________________________________________________________________'

# print the first $1 characters of the border, possibly using $2 as char
border () {
    n="$1"
    c="${2-_}"
    echo "${_border[1,$((n))]}" | tr '_' "$c"
}



# set a fancy prompt
myPrompt () {
    colorName="$@"
    hostColor=`eval esccolor ${colorName}`

    hostWidth=${#HOST}
    c=$COLUMNS
    if [ $(id -u) -eq 0 ]; then
        b=`eval border $((c - 4 - hostWidth)) '\#' `
        b2=`eval border 2 '\#' `
    else
        b=`eval border $((c - 4 - hostWidth)) `
        b2=`eval border 2 `
    fi
    coloredHost="%{${hostColor}%}${HOST}%{${colorOff}%}"
    line1="${b} ${coloredHost} ${b2}"$'\n'

    dirStuff='%(4~,.../,)%3~'
    dirBlue=`eval esccolor blue bold`

    line2="%n ${WINDOW} %{${dirBlue}%}${dirStuff}%{${colorOff}%}%# "

    export PS1="${line1}${line2}"
}


